blog/models.py
from blog import db
from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    image_file = db.Column(db.String(20), nullable=False, default='default.jpg')
    password = db.Column(db.String(60), nullable=False)
    # posts = db.relationship('Post', backref='author', lazy=True)

    def __repr__(self):
        return f'User({self.id}, {self.username}, {self.email}, {self.password}, {self.image_file})'

blog/user/forms.py
from flask import flash
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, EqualTo, Length, Email, ValidationError
from blog.models import User


class RegistrationForm(FlaskForm):
    username = StringField('Имя пользователя', validators=[DataRequired(), Length(min=4, max=20)])
    email = StringField('Емайл', validators=[DataRequired(), Email()])
    password = PasswordField('Пароль', validators=[DataRequired()])
    confirm_password = PasswordField('Подтвердите пароль', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Войти')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            flash('Это имя уже занято. Пожалуйста, выберите другое', 'danger')
            raise ValidationError('That username is taken. Please choose a different one')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            flash('Этот емайл уже занят. Пожалуйста, введите другой', 'danger')
            raise ValidationError('That email is taken. Please choose a different one')


class LoginForm(FlaskForm):
    email = StringField('Емайл', validators=[DataRequired(), Email()])
    password = PasswordField('Пароль', validators=[DataRequired()])
    remember = BooleanField('Запомнить меня')
    submit = SubmitField('Войти')

blog/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt

db = SQLAlchemy()
bcrypt = Bcrypt()


def create_app():
    app = Flask(__name__)
    app.config.from_pyfile('settings.py')
    db.init_app(app)
    bcrypt.init_app(app)
    from blog.main.routes import main
    from blog.user.routes import users

    app.register_blueprint(main)
    app.register_blueprint(users)

    return app
    

blog/main/routes.py
from flask import Blueprint, render_template

main = Blueprint('main', __name__)


@main.route('/')
def home():

    return render_template('index.html', title='Главная')


@main.route('/blog')
def blog():
    return render_template('index.html', title='Блог')


@main.route('/html_page')
def html_page():
    return render_template('html_page.html')


@main.route('/css_page')
def css_page():
    return render_template('css_page.html')


@main.route('/js_page')
def js_page():
    return render_template('js_page.html')


@main.route('/python_page')
def python_page():
    return render_template('python_page.html')


@main.route('/flask_page')
def flask_page():
    return render_template('flask_page.html')


@main.route('/django_page')
def django_page():
    return render_template('django_page.html')

blog/user/routes.py
import os
import shutil
from flask import Blueprint, render_template, flash, url_for
from werkzeug.utils import redirect

from blog import bcrypt, db
from blog.models import User
from blog.user.forms import RegistrationForm, LoginForm

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()

        full_path = os.path.join(os.getcwd(), 'blog/static', 'profile_pics', user.username)
        if not os.path.exists(full_path):
            os.mkdir(full_path)
        shutil.copy(f'{os.getcwd()}/blog/static/profile_pics/default.jpg', full_path)
        flash('Ваш аккаунт был создан. Вы можете войти на блог', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form, title='Регистрация', legend='Регистрация')


@users.route('/login', methods=['GET', 'POST'])
def login():
    return 'hello'

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css' ) }}"> 
    {% block title %}
        {% if title %}
            <title>Mike do IT - {{ title }}</title>
        {% else %}
            <title>Mike do IT</title>
        {% endif %}
    {% endblock %}
</head>
<body>
    <div class="wrapper">
        {% block menu %}
            <header class="header">
                <div class="logo">
                    <img src="{{ url_for('static', filename='img/logo.png') }}" alt="logo">
                </div>

                <ul class="main_menu">
                    <li><a href="/"><p>Главная</p></a></li>
                    <li><a href="#"><p>Блог</p></a></li>
                    <li><a href="{{ url_for('users.register' ) }}"><p>Регистрация</p></a></li>
                    <li><a href="#"><p>Логин</p></a></li>
                    <li><a href="#"><p>Аккаунт</p></a></li>
                    <li><a href="#"><p>Создать</p></a></li>
                    <li><a href="#"><p>Выход</p></a></li>
                </ul>
            </header>
        {% endblock menu %}


        {% block content %}

        {% endblock content %}
    
    
        {% block main_page %}
        <div class="content">
                
        </div>
        {% endblock main_page %}
    
    
        {% block footer %}
            <footer class="footer">
                <a href="https://github.com/Python4k/mikedoit_flask">https://github.com/Python4k/mikedoit_flask</a>
            </footer>
        {% endblock footer %}
    </div>
</body>
</html>

blog/templates/css_page.html
{% extends 'base.html' %}

{% block content %}
    
{% endblock %}

blog/templates/django_page.html
{% extends 'base.html' %}

{% block content %}
    
{% endblock %}

blog/templates/flask_page.html
{% extends 'base.html' %}

{% block content %}
    
{% endblock %}

blog/templates/html_page.html
{% extends 'base.html' %}

{% block content %}
    
{% endblock %}

blog/templates/index.html
{% extends 'base.html' %}



{% block main_page %}

    <div class="wrapper">
        <div class="info">
            <div class="description">
                <p class="names">Mike do IT Web development</p>
                <div class="desc">
                    <ul class="checkmark">
                        <a href="{{ url_for('main.html_page' ) }}">
                            <li>HTML</li>
                        </a>
                        <a href="{{ url_for('main.css_page' ) }}">
                            <li>CSS</li>
                        </a>
                        <a href="{{ url_for('main.python_page' ) }}">
                            <li>PYTHON</li>
                        </a>
                        <a href="{{ url_for('main.js_page' ) }}">
                            <li>JAVASCRIPT</li>
                        </a>
                        <a href="{{ url_for('main.flask_page' ) }}">
                            <li>FLASK</li>
                        </a>
                        <a href="{{ url_for('main.django_page' ) }}">
                            <li>DJANGO</li>
                        </a>
                    </ul>
                </div>
            </div>
        </div>
    </div>

{% endblock main_page %}

blog/templates/js_page.html
{% extends 'base.html' %}

{% block content %}
    
{% endblock %}

blog/templates/python_page.html
{% extends 'base.html' %}

{% block content %}
    
{% endblock %}

blog/templates/register.html
{% extends 'layout.html' %}

{% block content %}

<div class="login_form">
    <form action="" method="POST">

        {{ form.hidden_tag() }}
            <legend class="legend">{{ legend }}</legend>

                {% if form.username.errors %}
                {{ form.username(class='form-post-title is-invalid', placeholder='Имя пользователя') }}
                <div class="invalid-feedback">
                    {% for errors in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.username(class='form-post-title', placeholder='Имя пользователя') }}
                {% endif %}

                {% if form.email.errors %}
                {{ form.email(class='form-post-title is-invalid', placeholder='Емайл') }}
                <div class="invalid-feedback">
                    {% for errors in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.email(class='form-post-title', placeholder='Емайл') }}
                {% endif %}

                {% if form.password.errors %}
                {{ form.password(class='form-post-title is-invalid',  placeholder='Пароль') }}
                <div class="invalid-feedback">
                    {% for errors in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.password(class='form-post-title',  placeholder='Пароль') }}
                {% endif %}

                {% if form.confirm_password.errors %}
                {{ form.confirm_password(class='form-post-title is-invalid',  placeholder='Подтвердите пароль') }}
                <div class="invalid-feedback">
                    {% for errors in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.confirm_password(class='form-post-title',  placeholder='Подтвердите пароль') }}
                {% endif %}


        <div class="form-group">
            {{ form.submit(class='btn_sign_in') }}
        </div>

    </form>
</div>

<div class="border-top">
    <small class="text-muted">
        Уже есть аккаунт? <a class='ml-2' href="{{ url_for('users.login')}}">Войти</a>
    </small>
</div>
</div>

{% endblock %}